### PR TITLE
Unify draw_residual methods

### PR DESCRIPTION
**Pull request by alexpearce**
This unifies the `plotting.draw_residual_ulh` and `plotting.draw_residual_blh` interfaces, in particular such that they both support `show_errbars`. It also allows the line at x = 0 to be disabled, and adds a `kwargs` to both methods which is passed to the `ax.errorbar` or `ax.bar` calls. Now you can do things like:

```
likelihood.draw_residual(minuit, norm=True, show_errbars=False,
                         color='k', lw=0, zero_line=False)
```

This will create a pull (normalised residual) plot with black bars that have no borders, and without the red x = 0 line.

The implementation is the creation of a `draw_residuals` method that does the actual plotting, and having `plotting.draw_residual_ulh` and `plotting.draw_residual_blh` use it. The actual residual computation is still in the specific methods.

---

I've updated the docstrings in the `(Un)BinnedLH.draw_residual` methods, and added the `plotting.draw_residual` method to the utility section of the HTML documentation.

I haven't committed the changes to the `.c` files. I only edited `probfit/costfunc.pyx`, but some other files were updated as I was developing, was a lot of stuff that didn't seem relevant. But I've not worked on a Cython project before, so let me know I should add any of them.

All the tests pass, but I haven't added a new one for this; I think #63 would need to be addressed before I can do much there.

### CODE REVIEW

**Comment by cdeil** [comment]
@alexpearce - Thanks!

Now that #63 is merged and working (thanks to you!), could you add a test here?

Concerning when to update C files generated from Cython: I would suggest to remove the C files from the repo. Most Cython projects don't keep them in the repo, and we've done that for `iminuit` as well. People that get the dev version are OK with the Cython dependency, and for release source tarballs the C files will be included (something to watch out for when doing the next release).

@alexpearce - I don't have time to work on `probfit` this week. If you do, please make a separate PR removing the `C` files. If no, please file a separate reminder issue.

**Comment by alexpearce** [comment]
I will do the Cython-related cleanup soon, but opened #72 anyway as a reminder to myself.

After running the tests, the baselines are inconsistent between `UnbinnedLH` and `BinnedLH`. As examples, here are the results of `test_draw_residual_ulh` and `test_draw_residual_blh`, in that order:

draw_residual_ulh
draw_residual_blh

The `BinnedLH` residuals have caps on the errorbars, unlike the `UnbinnedLH` ones. I don't have much of a preference, but I will go with no caps (`capsize=0`) unless there are complaints.

I'm not sure what to do about errorbars along the x-axis. Really, if the users asks for `show_errbars=True` then they might expect both x and y errors, whereas now both ULH and BLH don't draw them. However, you do in some sense 'see' these when you ask for `show_errbars=False`, because a bar graph is drawn that shows the extent in x in which the pull is computed.

For now, I will add x-errorbars, remove the caps, and update the baselines accordingly.

**Comment by alexpearce** [comment]
I guess the tests are failing now because I haven't committed the Cython build files, and these aren't created on Travis. Does that sound right @cdeil?

For now I can just add them, until #72 and #69 are addressed.

**Comment by cdeil** [comment]
Yes, I think currently we're running
```
python setup.py build_ext -i
```
which isn't configure to notice that the `C` files are outdated or run Cython
https://github.com/iminuit/probfit/blob/master/.travis.yml#L24

For now, you could add the new C files in this PR, or add the `make cython` command to the travis-ci file here.
See https://github.com/iminuit/probfit/blob/master/Makefile#L57

**Comment by alexpearce** [comment]
Thanks. I'll add the C files for now, and work on overhauling the Travis stuff in another PR.

**Pull request merged**
